### ISSUE TITLE
Error launching SMS flood

### ISSUE THREAD

**Issue by ArnichQP** [LimerBoy/Impulse#24]
Haven't experienced this problem before the update.

Traceback (most recent call last):
  File "impulse.py", line 57, in <module>
    duration=time, name=method, threads=threads, target=target
  File "C:\Users\Intel\Desktop\Impulse DoS\tools\method.py", line 53, in __enter__
    self.method = GetMethodByName(self.name)
  File "C:\Users\Intel\Desktop\Impulse DoS\tools\method.py", line 25, in GetMethodByName
    module = __import__(dir, fromlist=["object"])
  File "C:\Users\Intel\Desktop\Impulse DoS\tools\SMS\main.py", line 5, in <module>
    __services = request.getServices()
  File "C:\Users\Intel\Desktop\Impulse DoS\tools\SMS\sendRequest.py", line 11, in getServices
    return json.load(services)["services"]
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4077: character maps to <undefined>

**Comment by Arniuha744** [comment]
![intl](https://user-images.githubusercontent.com/65954132/82894631-8cb90f00-9f5b-11ea-9643-cba2bf7d4cb8.png)

**Comment by K1ngSoul** [comment]
Дебил блять, ДЕБИЛ

**Comment by LimerBoy** [comment]
Download python 3.8

**Comment by K1ngSoul** [comment]
> 
> 
> Download python 3.8

лимер, где мой спайс блять

**Comment by K1ngSoul** [comment]
Посмотрите на меня я ДАУН!! Скачал python 3.6 и думаю почему я даун

**Comment by Arniuha744** [comment]
![intl](https://user-images.githubusercontent.com/65954132/82899048-fab50480-9f62-11ea-8a6b-b0d741e02651.png)
Python updated to 3.8, facing the same issue.

**Comment by LimerBoy** [comment]
Try run in cmd 'chcp 65001' and start impulse

**Comment by ArnichQP** [comment]
Running 'chcp 65001' returns 'Active code page: 65001'. Starting impulse with SMS method gives the same 'UnicodeDecodeError' issue.

**Comment by LimerBoy** [comment]
> Running 'chcp 65001' returns 'Active code page: 65001'. Starting impulse with SMS method gives the same 'UnicodeDecodeError' issue.

Download again

**Comment by ArnichQP** [comment]
Working like a charm. Fascinating work!
