### ISSUE TITLE
No Module named tools.sms.main

### ISSUE THREAD

**Issue by BeatKO** [LimerBoy/Impulse#9]
Hi
i'm getting this error when i start the impulse.py

```
Failed import some modules
Traceback (most recent call last):
  File "impulse.py", line 75, in <module>
    main()
  File "impulse.py", line 68, in main
    from tools.SMS.main import SMS_ATTACK
ImportError: No module named tools.SMS.main
```

**Comment by 0xPh0enix** [comment]
Dude, clone all files from this repo..

**Comment by BeatKO** [comment]
Cloned all the files still getting this error..

**Comment by LimerBoy** [comment]
Try run on windows

**Comment by BeatKO** [comment]
Works from powershell , thanks.

**Comment by LimerBoy** [comment]
No, it's just sms flooder.
